# The two sibling repos DocBoss compiles from, and exactly what it takes.
#
# Both are consumed by ABSOLUTE PATH and SOURCE PULL -- the workspace's pinned
# pattern -- not as submodules and not as copies.  A fix made upstream reaches
# DocBoss when the pin below is bumped; nothing is copied, so nothing drifts
# silently.  What gets built is always the sibling's HEAD; the pin only warns.
# When you intentionally advance a sibling, bump its SHA here in the SAME
# commit that depends on the new code, and diff the pulled files themselves,
# not just the SHA (C:\source\CLAUDE.md, "A stale pin is not the same as a
# stale build").
#
# Two rules make the pull safe:
#
# 1. Pulled units keep their own includes.  A quoted #include resolves in the
#    including file's own folder first, so MDBoss's FileScan.cpp gets MDBoss's
#    PathUtf8.h and PDFBoss's TocGen.cpp gets PDFBoss's -- never each other's,
#    and never DocBoss's.  The two apps' code lives in different namespaces
#    (mdboss::, pdfboss::), so both PathUtf8.cpp can be linked side by side.
#
# 2. DocBoss's OWN code never includes a sibling header by bare name.  Both
#    siblings ship a PathUtf8.h, a Config.h, a Version.h, an Updater.h..., so
#    "PathUtf8.h" from an include path would be a coin toss.  Instead this file
#    generates forwarding headers under ${DOCBOSS_PULL_INCLUDE}: DocBoss code
#    writes #include "mdboss/FileScan.h" or "pdfboss/ViewerPane.h", and only
#    the headers named in the lists below exist there.  A header not listed
#    cannot be included by accident.
#
# A new #include in a pulled .cpp that names a sibling unit not listed here
# shows up as undefined symbols at link time.  Add the unit to the list.

find_package(Git QUIET)

function(docboss_check_pin dir expected name)
    if(NOT Git_FOUND)
        return()
    endif()
    execute_process(COMMAND ${GIT_EXECUTABLE} -C "${dir}" rev-parse HEAD
                    OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE
                    RESULT_VARIABLE _rc ERROR_QUIET)
    if(_rc EQUAL 0 AND NOT _head STREQUAL "${expected}")
        message(WARNING
            "${name} (${dir}) is at ${_head}\n"
            "  but this DocBoss pins ${expected}.\n"
            "  Behaviour may differ. If you intentionally advanced ${name},\n"
            "  update its *_EXPECTED_COMMIT in cmake/Siblings.cmake.")
    elseif(_rc EQUAL 0)
        message(STATUS "${name} pinned commit OK (${expected})")
    endif()
endfunction()

set(MDBOSS_DIR "C:/source/MDBoss" CACHE PATH "Path to the MDBoss repo")
set(MDBOSS_EXPECTED_COMMIT "4e41ac7e5f5ec58b22c884a651606d5f8f456488")
set(PDFBOSS_DIR "C:/source/PDFBoss" CACHE PATH "Path to the PDFBoss repo")
set(PDFBOSS_EXPECTED_COMMIT "87782f6a85db221bcefad68d7a0eb3354d8aa72e")

foreach(_probe "${MDBOSS_DIR}/MDBossCpp/app/AppIdentity.h"
               "${PDFBOSS_DIR}/PDFBossCpp/app/PdfDocument.h")
    if(NOT EXISTS "${_probe}")
        message(FATAL_ERROR "DocBoss needs ${_probe}; clone the sibling repo "
                            "or point MDBOSS_DIR / PDFBOSS_DIR at it.")
    endif()
endforeach()

docboss_check_pin("${MDBOSS_DIR}" "${MDBOSS_EXPECTED_COMMIT}" "MDBoss")
docboss_check_pin("${PDFBOSS_DIR}" "${PDFBOSS_EXPECTED_COMMIT}" "PDFBoss")

set(MDBOSS_APP "${MDBOSS_DIR}/MDBossCpp/app")
set(PDFBOSS_APP "${PDFBOSS_DIR}/PDFBossCpp/app")

# ---- What is pulled -------------------------------------------------------
#
# Headless units go into docboss_core with DocBoss's own headless code, so the
# tests can link them without wxWidgets; GUI units go into the exe.

set(MDBOSS_CORE_UNITS
    AppIdentity FileScan TextSearch LinkTarget PathUtf8 InternalNotes
    TechNotes Templates Favorites FileAssoc Updater Config)
set(MDBOSS_GUI_UNITS
    PreviewPane FindBar FindInFilesDialog DocumentWatcher OutlinePanel
    PathListPanel InternalDialogs SingleInstance UpdaterHttp DropTarget
    FoldersDialog)
# Headers with no .cpp of their own that DocBoss code includes directly.
set(MDBOSS_HEADER_ONLY LogoAsset)

set(PDFBOSS_CORE_UNITS PdfDocument TocGen Metadata PathUtf8)
set(PDFBOSS_GUI_UNITS ViewerPane TopicsPane)

# ---- Forwarding headers ---------------------------------------------------

set(DOCBOSS_PULL_INCLUDE "${CMAKE_BINARY_DIR}/pull")

function(docboss_forward prefix app_dir units)
    foreach(_unit ${units})
        set(_target "${app_dir}/${_unit}.h")
        if(NOT EXISTS "${_target}")
            continue()   # a unit with no header of its own (UpdaterHttp)
        endif()
        set(_out "${DOCBOSS_PULL_INCLUDE}/${prefix}/${_unit}.h")
        set(_text "// Generated by cmake/Siblings.cmake -- do not edit.\n#include \"${_target}\"\n")
        if(EXISTS "${_out}")
            file(READ "${_out}" _old)
        else()
            set(_old "")
        endif()
        if(NOT _old STREQUAL _text)   # rewrite only on change: no rebuild storm
            file(WRITE "${_out}" "${_text}")
        endif()
    endforeach()
endfunction()

docboss_forward(mdboss "${MDBOSS_APP}"
    "${MDBOSS_CORE_UNITS};${MDBOSS_GUI_UNITS};${MDBOSS_HEADER_ONLY}")
docboss_forward(pdfboss "${PDFBOSS_APP}"
    "${PDFBOSS_CORE_UNITS};${PDFBOSS_GUI_UNITS}")

function(docboss_sources out app_dir units)
    set(_list "")
    foreach(_unit ${units})
        list(APPEND _list "${app_dir}/${_unit}.cpp")
    endforeach()
    set(${out} "${_list}" PARENT_SCOPE)
endfunction()

docboss_sources(MDBOSS_CORE_SOURCES "${MDBOSS_APP}" "${MDBOSS_CORE_UNITS}")
docboss_sources(MDBOSS_GUI_SOURCES "${MDBOSS_APP}" "${MDBOSS_GUI_UNITS}")
docboss_sources(PDFBOSS_CORE_SOURCES "${PDFBOSS_APP}" "${PDFBOSS_CORE_UNITS}")
docboss_sources(PDFBOSS_GUI_SOURCES "${PDFBOSS_APP}" "${PDFBOSS_GUI_UNITS}")

# ---- mdrender and MuPDF ---------------------------------------------------

if(NOT TARGET mdrender)
    add_subdirectory("${MDBOSS_DIR}/MDBossCpp/mdrender"
                     "${CMAKE_BINARY_DIR}/mdboss_mdrender")
endif()

# MuPdf.cmake defines the `mupdf` interface target and checks the 1.28.2 pin.
list(APPEND CMAKE_MODULE_PATH "${PDFBOSS_DIR}/PDFBossCpp/cmake")
include(MuPdf)

# The render assets (stylesheets, highlight.js, KaTeX, mermaid, the page
# template) are MDBoss's, used as they are.
set(MDBOSS_ASSETS "${MDBOSS_DIR}/assets")
